# modraw-server handlers

- name: Restart modraw-server
  ansible.builtin.systemd:
    name: "{{ binary_name }}"
    state: restarted
    daemon_reload: yes

- name: Reload Nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
